version: '3.8'

services:
  # PostgreSQL with pgvector
  postgres:
    image: ankane/pgvector:latest
    container_name: agentic-wallet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agentic_wallet
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - agentic-wallet-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: agentic-wallet-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - agentic-wallet-network

  # Redis Commander (optional - for Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: agentic-wallet-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - agentic-wallet-network
    profiles:
      - tools

  # pgAdmin (optional - for PostgreSQL GUI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: agentic-wallet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agentic-wallet.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - agentic-wallet-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  agentic-wallet-network:
    driver: bridge
